### ISSUE TITLE
Naming of IndexedArrays

### ISSUE THREAD

**Issue by ScottPJones** [garrison/UniqueVectors.jl#4]
I was wondering about if `IndexedArrays` is the most appropriate name for this functionality,
which is not at all like what is called `IndexedArrays` in other languages that I've seen
(where it is used to distinguish between vectors and associative arrays (i.e. Dicts in Julia)).
Since values are unique, `findfirst` doesn't seem like the appropriate name/interface for what it does.
It really seems like this is a type of `OrderedSet`, which is present in https://github.com/JuliaLang/DataStructures.jl (I haven't looked yet, this may be a better/faster implementation, if so, maybe it should be used to replace the one in DataStructures).

> (More generally, one might want an abstract type that represents any bidirectional mapping between two different sets (without one of them necessarily being contiguous integers from 1 to N). In this cast, using findfirst may not be the appropriate interface, and I'd welcome any comments on this.)

I haven't seen anyplace else that implements that, it sounds very interesting, to be able to build a fast, bi-directional, one-to-one mapping structure.  Maybe that could be called a `BiDict` or `OneToOneMap`.
You could use two `OrderedSet` to get to an integer index, and have a `Vector{Pair{K,V}}` to hold the actual key / value pairs.  When inserting, you'd need to check that both K and V are not present in their respective `OrderedSet`s, before adding them to the `Vector` of Pairs, and adding the mapping in both `OrderedSet`s.

Hopefully what I said above isn't all wet!  Let me know!

**Comment by garrison** [comment]
See also https://github.com/JuliaLang/METADATA.jl/pull/2236#issuecomment-76848472

**Comment by ScottPJones** [comment]
Ah, thanks - that was before I started with Julia, so I'd missed it.
Maybe `UniqueVector`?  That doesn't imply having the rest of the `Set` interface (although, why don't you want the `Set` functions), and also is more correct in saying `Vector` instead of `Array`, and makes clear the most important point about these, that the _values_ are unique.

**Comment by garrison** [comment]
Oh interesting, it looks like LLVM [has a class called `UniqueVector`](http://llvm.org/docs/doxygen/html/classllvm_1_1UniqueVector.html) that has similar functionality to that of this package.  So perhaps this is indeed a better name, especially since it is already in use elsewhere.

**Comment by benninkrs** [comment]
@garrison Thanks for contributing this to the community, For a while I've thought such a data structure would be useful, and just now discovered your package.

Regarding the name, I'm not sure `UniqueVector` is the best.  To me it suggests that the vector as a whole is unique. Besides, I don't think the fact that the values are unique is really the defining feature.  Rather, I think the structure is best defined by the fact that it supports both `Vector`-like access and `Dict`-like access.  To me the most obvious name would be `VectorDict`.
