### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [garrison/UniqueVectors.jl#8]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by garrison** [comment]
I think this is in error -- see https://github.com/garrison/UniqueVectors.jl/commit/dcc5fd51af87d7f755ab2b61cac1aa3b6c3b7b12#comments

**Comment by KristofferC** [comment]
This is actually for "IndexedArrays" (https://github.com/JuliaRegistries/General/blob/4cdda26f7ecc0caa6cb2e3e6ae248e14c211f4e5/I/IndexedArrays/Package.toml) which points to this repo. That should be ok to remove, right? UniqueVectors.jl itself will not be touch.

**Comment by garrison** [comment]
Ahh, sounds perfect.  IndexedArrays is indeed the older name of this package (see #4), and the older package is deprecated and predates julia 1.0 entirely.  So no problem then.  Thanks for the reply!
